import { createHash } from 'node:crypto';
import { readFile } from 'node:fs/promises';
import path from 'node:path';

import type { ShapeSpec } from '../../src/core/types';
import {
  QUOTA_CO_DOOR_PALETTE,
  QUOTA_CO_DOOR_SOURCE_DEFINITIONS,
} from '../../src/props/doorManifest';
import { compileStaticPropSource } from './importer';

interface ImportedQuotaCoDoorArt {
  readonly id: 'door';
  readonly projection: 'plan';
  readonly sourceFile: string;
  readonly sourceFiles: readonly string[];
  readonly sourceSha256: string;
  readonly paletteDefaults: typeof QUOTA_CO_DOOR_PALETTE;
  readonly variants: Readonly<Record<string, readonly ShapeSpec[]>>;
  readonly sourceSvgVariants: Readonly<Record<string, string>>;
}

function assertSafeSource(sourceFile: string, svg: string): void {
  if (/<(?:text|script|foreignObject)\b/i.test(svg)) {
    throw new Error(`${sourceFile}: world sprites cannot contain rendered text, script, or foreignObject`);
  }
  if (/\b(?:href|xlink:href|on[a-z]+)\s*=/i.test(svg)) {
    throw new Error(`${sourceFile}: external references and event attributes are forbidden`);
  }
}

export async function compileQuotaCoDoorArt(
  inputDir: string,
  sourcePathPrefix: string,
): Promise<readonly ImportedQuotaCoDoorArt[]> {
  const variants: Record<string, readonly ShapeSpec[]> = {};
  const sourceSvgVariants: Record<string, string> = {};
  const sourceFiles: string[] = [];
  const digest = createHash('sha256');
  for (const definition of QUOTA_CO_DOOR_SOURCE_DEFINITIONS) {
    const sourceFile = path.posix.join(
      sourcePathPrefix.replaceAll('\\', '/'),
      definition.sourceFile,
    );
    const source = await readFile(path.join(inputDir, definition.sourceFile), 'utf8');
    assertSafeSource(sourceFile, source);
    sourceFiles.push(sourceFile);
    digest.update(definition.sourceFile).update('\0').update(source).update('\0');
    variants[definition.key] = compileStaticPropSource(sourceFile, source, {
      id: 'door',
      projection: 'plan',
      paletteDefaults: QUOTA_CO_DOOR_PALETTE,
    });
    sourceSvgVariants[definition.key] = source;
  }
  return [{
    id: 'door',
    projection: 'plan',
    sourceFile: sourcePathPrefix.replaceAll('\\', '/'),
    sourceFiles,
    sourceSha256: digest.digest('hex'),
    paletteDefaults: QUOTA_CO_DOOR_PALETTE,
    variants,
    sourceSvgVariants,
  }];
}

function quote(value: string): string {
  return JSON.stringify(value);
}

function emitShape(shape: ShapeSpec): string {
  const fields = [`d: ${quote(shape.d)}`];
  if (shape.fill !== undefined) fields.push(`fill: ${quote(shape.fill)}`);
  if (shape.stroke !== undefined) fields.push(`stroke: ${quote(shape.stroke)}`);
  if (shape.strokeWidth !== undefined) fields.push(`strokeWidth: ${shape.strokeWidth}`);
  if (shape.strokeLinecap !== undefined) fields.push(`strokeLinecap: ${quote(shape.strokeLinecap)}`);
  if (shape.strokeLinejoin !== undefined) fields.push(`strokeLinejoin: ${quote(shape.strokeLinejoin)}`);
  if (shape.opacity !== undefined) fields.push(`opacity: ${shape.opacity}`);
  if (shape.silhouette !== undefined) fields.push(`silhouette: ${shape.silhouette}`);
  return `{ ${fields.join(', ')} }`;
}

export function emitQuotaCoDoorArt(
  imports: readonly ImportedQuotaCoDoorArt[],
): string {
  const lines = [
    "import type { ImportedPropArt } from '../authoredArt';",
    '',
    '// Generated by `npm run doors:import`. Do not edit by hand.',
    'export const QUOTA_CO_DOOR_ART = [',
  ];
  for (const imported of imports) {
    lines.push('  {');
    lines.push(`    id: ${quote(imported.id)},`);
    lines.push(`    projection: ${quote(imported.projection)},`);
    lines.push(`    sourceFile: ${quote(imported.sourceFile)},`);
    lines.push(`    sourceFiles: ${JSON.stringify(imported.sourceFiles)},`);
    lines.push(`    sourceSha256: ${quote(imported.sourceSha256)},`);
    lines.push(`    paletteDefaults: ${JSON.stringify(imported.paletteDefaults)},`);
    lines.push('    variants: {');
    for (const [key, shapes] of Object.entries(imported.variants)) {
      lines.push(`      ${quote(key)}: [`);
      for (const shape of shapes) lines.push(`        ${emitShape(shape)},`);
      lines.push('      ],');
    }
    lines.push('    },');
    lines.push('    sourceSvgVariants: {');
    for (const [key, svg] of Object.entries(imported.sourceSvgVariants)) {
      lines.push(`      ${quote(key)}: ${quote(svg)},`);
    }
    lines.push('    },');
    lines.push('  },');
  }
  lines.push('] as const satisfies readonly ImportedPropArt[];');
  return `${lines.join('\n')}\n`;
}
