import { createHash } from 'node:crypto';
import { readFile } from 'node:fs/promises';
import path from 'node:path';

import type { ShapeSpec } from '../../src/core/types';
import {
  IRIS_HARDWARE_SOURCE_DEFINITIONS,
  type IrisHardwareSourceDefinition,
} from '../../src/props/irisHardwareManifest';
import { fitCanonicalIrisHardwareSourceSvg } from './canonicalIrisHardwareFit';
import { compileStaticPropSource } from './importer';

interface ImportedIrisHardwareArt {
  readonly id: string;
  readonly projection: IrisHardwareSourceDefinition['projection'];
  readonly sourceFile: string;
  readonly sourceSha256: string;
  readonly paletteDefaults: IrisHardwareSourceDefinition['paletteDefaults'];
  readonly variants: Readonly<Record<string, readonly ShapeSpec[]>>;
  readonly sourceSvgVariants: Readonly<Record<string, string>>;
}

function hash(source: string): string {
  return createHash('sha256').update(source).digest('hex');
}

function assertSafeSource(sourceFile: string, svg: string): void {
  if (/<(?:text|script|foreignObject)\b/i.test(svg)) {
    throw new Error(`${sourceFile}: world sprites cannot contain text, script, or foreignObject`);
  }
  if (/\b(?:href|xlink:href|on[a-z]+)\s*=/i.test(svg)) {
    throw new Error(`${sourceFile}: external references and event attributes are forbidden`);
  }
}

export async function compileIrisHardwareArt(
  inputDir: string,
  sourcePathPrefix: string,
): Promise<readonly ImportedIrisHardwareArt[]> {
  const result: ImportedIrisHardwareArt[] = [];
  for (const definition of IRIS_HARDWARE_SOURCE_DEFINITIONS) {
    const sourceFile = path.posix.join(
      sourcePathPrefix.replaceAll('\\', '/'),
      definition.sourceFile,
    );
    const source = await readFile(path.join(inputDir, definition.sourceFile), 'utf8');
    assertSafeSource(sourceFile, source);
    const variants: Record<string, readonly ShapeSpec[]> = {};
    const sourceSvgVariants: Record<string, string> = {};
    const heights = definition.heights ?? [undefined];
    for (const height of heights) {
      const params: Readonly<Record<string, number>> =
        height === undefined ? {} : { height };
      const key = height === undefined ? '' : `height=${height}`;
      const fitted = fitCanonicalIrisHardwareSourceSvg(
        source,
        definition.id,
        params,
        undefined,
        128,
      );
      variants[key] = compileStaticPropSource(sourceFile, fitted, {
        id: definition.id,
        projection: definition.projection,
        paletteDefaults: definition.paletteDefaults,
      });
      sourceSvgVariants[key] = fitted;
    }
    result.push({
      id: definition.id,
      projection: definition.projection,
      sourceFile,
      sourceSha256: hash(source),
      paletteDefaults: definition.paletteDefaults,
      variants,
      sourceSvgVariants,
    });
  }
  return result;
}

function quote(value: string): string {
  return JSON.stringify(value);
}

function emitShape(shape: ShapeSpec): string {
  const fields = [`d: ${quote(shape.d)}`];
  if (shape.fill !== undefined) fields.push(`fill: ${quote(shape.fill)}`);
  if (shape.stroke !== undefined) fields.push(`stroke: ${quote(shape.stroke)}`);
  if (shape.strokeWidth !== undefined) fields.push(`strokeWidth: ${shape.strokeWidth}`);
  if (shape.strokeLinecap !== undefined) fields.push(`strokeLinecap: ${quote(shape.strokeLinecap)}`);
  if (shape.strokeLinejoin !== undefined) fields.push(`strokeLinejoin: ${quote(shape.strokeLinejoin)}`);
  if (shape.opacity !== undefined) fields.push(`opacity: ${shape.opacity}`);
  if (shape.silhouette !== undefined) fields.push(`silhouette: ${shape.silhouette}`);
  return `{ ${fields.join(', ')} }`;
}

export function emitIrisHardwareArt(imports: readonly ImportedIrisHardwareArt[]): string {
  const lines = [
    "import type { ImportedPropArt } from '../authoredArt';",
    '',
    '// Generated by `npm run iris-hardware:import`. Do not edit by hand.',
    'export const IRIS_HARDWARE_ART = [',
  ];
  for (const imported of imports) {
    lines.push('  {');
    lines.push(`    id: ${quote(imported.id)},`);
    lines.push(`    projection: ${quote(imported.projection)},`);
    lines.push(`    sourceFile: ${quote(imported.sourceFile)},`);
    lines.push(`    sourceSha256: ${quote(imported.sourceSha256)},`);
    lines.push(`    paletteDefaults: ${JSON.stringify(imported.paletteDefaults)},`);
    lines.push('    variants: {');
    for (const [key, shapes] of Object.entries(imported.variants)) {
      lines.push(`      ${quote(key)}: [`);
      for (const shape of shapes) lines.push(`        ${emitShape(shape)},`);
      lines.push('      ],');
    }
    lines.push('    },');
    lines.push('    sourceSvgVariants: {');
    for (const [key, svg] of Object.entries(imported.sourceSvgVariants)) {
      lines.push(`      ${quote(key)}: ${quote(svg)},`);
    }
    lines.push('    },');
    lines.push('  },');
  }
  lines.push('] as const satisfies readonly ImportedPropArt[];');
  return `${lines.join('\n')}\n`;
}
