import { readdir, readFile } from 'node:fs/promises';
import path from 'node:path';

import type { ShapeSpec } from '../../src/core/types';
import {
  WALL_BEVEL_PIECE_IDS,
  type WallBevelPieceId,
} from '../../src/tiles/wallBevelContract';
import { compileAuthoredSvg } from '../parts/importer';

export interface CompiledWallBevelPiece {
  readonly id: WallBevelPieceId;
  readonly shapes: readonly ShapeSpec[];
  readonly sourceFile: string;
}

export interface CompileWallBevelDirectoryOptions {
  inputDir: string;
  sourcePathPrefix: string;
}

export class WallBevelImportError extends Error {
  constructor(message: string) {
    super(`Wall bevel import: ${message}`);
    this.name = 'WallBevelImportError';
  }
}

function compareText(left: string, right: string): number {
  return left < right ? -1 : left > right ? 1 : 0;
}

function repositoryPrefix(value: string): string {
  const normalized = value.replaceAll('\\', '/').replace(/^\.\//, '').replace(/\/$/, '');
  if (!normalized || path.posix.isAbsolute(normalized) || normalized === '..' || normalized.startsWith('../')) {
    throw new WallBevelImportError('sourcePathPrefix must be repository-relative');
  }
  return normalized;
}

function validateLightingPaint(piece: WallBevelPieceId, shapes: readonly ShapeSpec[]): void {
  if (shapes.length === 0) throw new WallBevelImportError(`${piece} contains no shapes`);
  if (!shapes.some((shape) => shape.fill !== undefined)) {
    throw new WallBevelImportError(`${piece} must contain a filled face`);
  }

  for (const [index, shape] of shapes.entries()) {
    if (shape.silhouette !== false) {
      throw new WallBevelImportError(`${piece}/shape-${index + 1} must be detail/* art`);
    }
    for (const [label, paint] of [['fill', shape.fill], ['stroke', shape.stroke]] as const) {
      if (paint === undefined) continue;
      if (paint.startsWith('$')) {
        throw new WallBevelImportError(`${piece}/shape-${index + 1} ${label} cannot use palette tokens`);
      }
      if (paint !== '#FFFFFF' && paint !== '#000000') {
        throw new WallBevelImportError(
          `${piece}/shape-${index + 1} ${label} must be neutral #FFFFFF or #000000 lighting paint`,
        );
      }
    }
  }
}

/** Compile the complete 12-file kit atomically in memory. */
export async function compileWallBevelDirectory(
  options: CompileWallBevelDirectoryOptions,
): Promise<CompiledWallBevelPiece[]> {
  const prefix = repositoryPrefix(options.sourcePathPrefix);
  const entries = (await readdir(options.inputDir, { withFileTypes: true }))
    .sort((left, right) => compareText(left.name, right.name));
  const expectedFiles = new Set(WALL_BEVEL_PIECE_IDS.map((id) => `${id}.svg`));

  for (const entry of entries) {
    if (!entry.isFile() || !expectedFiles.has(entry.name)) {
      throw new WallBevelImportError(`unexpected source ${entry.name}`);
    }
  }
  const actualFiles = new Set(entries.map((entry) => entry.name));
  for (const expected of expectedFiles) {
    if (!actualFiles.has(expected)) throw new WallBevelImportError(`missing source ${expected}`);
  }

  const pieces: CompiledWallBevelPiece[] = [];
  for (const id of WALL_BEVEL_PIECE_IDS) {
    const filename = `${id}.svg`;
    const sourceFile = `${prefix}/${filename}`;
    const input = await readFile(path.join(options.inputDir, filename), 'utf8');
    const shapes = compileAuthoredSvg(input, {
      source: sourceFile,
      origin: { x: 0, y: 0 },
    });
    validateLightingPaint(id, shapes);
    pieces.push({ id, shapes, sourceFile });
  }
  return pieces;
}

function quote(value: string): string {
  return JSON.stringify(value);
}

function emitShape(shape: ShapeSpec): string {
  const properties = [`d: ${quote(shape.d)}`];
  if (shape.fill !== undefined) properties.push(`fill: ${quote(shape.fill)}`);
  if (shape.stroke !== undefined) properties.push(`stroke: ${quote(shape.stroke)}`);
  if (shape.strokeWidth !== undefined) properties.push(`strokeWidth: ${shape.strokeWidth}`);
  if (shape.opacity !== undefined) properties.push(`opacity: ${shape.opacity}`);
  if (shape.silhouette !== undefined) properties.push(`silhouette: ${shape.silhouette}`);
  return `{ ${properties.join(', ')} }`;
}

/** Deterministic runtime registry: no timestamps, absolute paths, or provenance. */
export function emitWallBevelRegistry(pieces: readonly CompiledWallBevelPiece[]): string {
  const lines = [
    "import type { WallBevelRegistry } from '../wallBevelContract';",
    '',
    '// Generated by `npm run walls:import`. Do not edit by hand.',
    'export const WALL_BEVEL_ART = {',
  ];
  for (const piece of pieces) {
    lines.push(`  ${quote(piece.id)}: [`);
    for (const shape of piece.shapes) lines.push(`    ${emitShape(shape)},`);
    lines.push('  ],');
  }
  lines.push('} as const satisfies WallBevelRegistry;');
  return `${lines.join('\n')}\n`;
}
